-- Create a new schema and tables

CREATE TABLE banks (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) UNIQUE NOT NULL
);

CREATE TABLE reviews (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text     CLOB,
    rating          NUMBER,
    review_date     DATE,
    sentiment_label VARCHAR2(20),
    sentiment_score NUMBER,
    bank_id         NUMBER,
    source          VARCHAR2(50),
    FOREIGN KEY (bank_id) REFERENCES banks(id)
);
